### PR TITLE
support for RSA signature for NauXmlFeed and added Sha512 to FileUpdateT...

### PR DESCRIPTION
**Pull request by halotron**
Is it interesting to add optional signed updates and sha512 to NAppUpdate?

### CODE REVIEW

**Comment by vbjay** [comment]
He may not want the product name changed in e51130d applied to his repo.

**Comment by synhershko** [comment]
indeed :)

**Comment by halotron** [comment]
lol, true that.
Sorry, will fix asap.

2015-10-11 1:20 GMT+02:00 Jay Asbury <notifications@github.com>:

**Comment by robinwassen** [comment]
I think this feature is great and something that should be implemented in some way into the library to provide proper security. The security model is sound where you both validate the XML with the public key and then validate the hash of each file to the hashes in the validated XML.

The only problem I have is that the white space changes in this PR makes reviewing it quite hard.

**Pull request closed without merging**
