### PR TITLE
Changing "or-not" to "or" on Version Condition

### PR DESCRIPTION
**Pull request by OleAlbers**
File should usually be replaced if it is lower the target version

### CODE REVIEW

**Comment by robinwassen** [comment]
I am sorry that I have not taken care of this yet, the update conditions are not that easy to understand so I will need to write a unit test in order to be confident that this change is correct.

FileCondition (what="below") will return true if the local binary is lower version than the one on the update source.

Condition of type OR will perform the update if the condition returns true. NOT will negate this.

So it sounds like this change is indeed correct.

**Comment by synhershko** [comment]
+1 I agree. Thanks @OleAlbers !

**Comment by robinwassen** [comment]
I will merge this, the more I think of it the more I am confident that it is correct.

Especially since the or-not ended up there after I rewrote some of the code.

**Comment by robinwassen** [comment]
Yes, I checked and before I changed around in the code the type as AND. But I think an OR would be more suitable. Will perform the merge.

**Pull request merged**
