### PR TITLE
Fix feedbuilder tool

### PR DESCRIPTION
**Pull request by vbjay**
Ignoring files only worked on files in the root folder.  All subdirectory files did not remember the ignored files in the tool.

### CODE REVIEW

**Comment by vbjay** [comment]
Ready to pull.  

Summary of changes:
* Fix ignore issue in feedbuilder
* Make feedbuilder process files in the background

**Comment by synhershko** [comment]
Thanks @vbjay. The changes to FeedBuilder look good and the rest look like just whitespace and an f/w version update.

The framework version of FeedBuilder doesn't really matter, it's a tool and you should probably have the latest version of the framework installed anyway. However, that isn't the case for the target platforms - the one you are trying to run an update process on. Can you please avoid compiling NAU for 4.0 and leave it 2.0? last time I was working on this I made sure there isn't anything important NAU is missing by using 2.0, I believe that still is the case.

**Comment by vbjay** [comment]
OK. I will revert the changes to the framework version to the library
projects later on today.

**Comment by robinwassen** [comment]
@synhershko - May I take care of merging these changes?

**Comment by synhershko** [comment]
Sure, go ahead

**Comment by vbjay** [comment]
Looking to rebase this.  Trying not to code stomp.

**Comment by vbjay** [comment]
Reworking with new branch

**Pull request closed without merging**
